### ISSUE TITLE
巨佬是否考虑简化一下？

### ISSUE THREAD

**Issue by sunsvip** [XuToWei/GameDevelopmentKit#12]
通用框架堆的插件越多越不通用，比如那些列出的要手动安装的插件完全不是必要、或者不是框架层需要的，如果能优化掉就好了。
不改任何GF和ET服务端的源码，通过中间件进行融合GF+ET，以简洁、优雅的方式完美融合GF+ET这两个双端最火的框架，会非常有市场需求

**Comment by XuToWei** [comment]
最简洁优雅的方式是用et重写gf，但是工作量比较大，暂时还没有精力和时间来这样处理。至于没必要的插件理论上除了et自带的其他的都可以删掉，GDK追求的是开发上的便利性，通用性的优先级较低。

**Comment by sunsvip** [comment]
> 最简洁优雅的方式是用et重写gf，但是工作量比较大，暂时还没有精力和时间来这样处理。至于没必要的插件理论上除了et自带的其他的都可以删掉，GDK追求的是开发上的便利性，通用性的优先级较低。

现在工程拉下来之后几百个报错，不确定是不是那6个需要手动安装的插件造成的，UniTask也丢失了

**Comment by XuToWei** [comment]
按运行文档操作即可
