### ISSUE TITLE
mac上gdk导表失败 Game : bash: dotnet: command not found

### ISSUE THREAD

**Issue by Wxwind** [XuToWei/GameDevelopmentKit#13]
mac上gdk导表会报dotnet命令找不到，但是我在shell里面执行dotnet是确定安装的（并且～/.bashrc也配置了环境变量）。我把shelltool代码放到独立的.net控制台项目执行dotnet --version也没有问题。唯独在unity里会报错，这是什么原因。
![image](https://github.com/user-attachments/assets/2b7d2c84-ed88-4d83-a3b6-ce320ce68b4f)

**Comment by Wxwind** [comment]
![image](https://github.com/user-attachments/assets/ed15e6bb-0621-458d-9f1c-99d1a5d58950)
手动传入dotnet路径是可以的

**Comment by XuToWei** [comment]
tks，已修复
