### ISSUE TITLE
大佬辛苦了。

### ISSUE THREAD

**Issue by TapsJoy** [XuToWei/GameDevelopmentKit#2]
gf  的资源管理有点麻烦，会不会考虑接入  YooAsset  这样的资源管理工程？

**Comment by XuToWei** [comment]
目前不会考虑接入YooAsset，接入对gf内部侵入性太强，gf的资源打包部分已经扩展支持简单操作出包了，至于业务逻辑上的使用两者差距很小，gf目前也拓展支持了UniTask

**Comment by TapsJoy** [comment]
好的。
