### ISSUE TITLE
FastScriptReload的依赖插件版本报错。

### ISSUE THREAD

**Issue by Maybank01** [XuToWei/GameDevelopmentKit#4]
拉下工程编译，提示

```
Microsoft.CodeAnalysis references strong named System.Text.Encoding.CodePages 
Assembly references: 4.0.2.0 
Found in project: 5.0.0.0.
```

这个不影响工程运行。不知道是我环境的问题还是这个问题无关紧要，不需要解决

**Comment by XuToWei** [comment]
可以去掉Assembly Version Validation选项解决，目前该问题已经提交给FastScriptReload作者了
https://github.com/handzlikchris/FastScriptReload/issues/72
